// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/person.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 817311707611462368),
    name: 'OBPerson',
    lastPropertyId: const obx_int.IdUid(5, 1013401106798143489),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8347214923850553636),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8578515136220843738),
        name: 'firstName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1190439392344694794),
        name: 'middleName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7252681734961514324),
        name: 'lastName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1013401106798143489),
        name: 'number',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 817311707611462368),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    OBPerson: obx_int.EntityDefinition<OBPerson>(
      model: _entities[0],
      toOneRelations: (OBPerson object) => [],
      toManyRelations: (OBPerson object) => {},
      getId: (OBPerson object) => object.id,
      setId: (OBPerson object, int id) {
        object.id = id;
      },
      objectToFB: (OBPerson object, fb.Builder fbb) {
        final firstNameOffset = fbb.writeString(object.firstName);
        final middleNameOffset = object.middleName == null
            ? null
            : fbb.writeString(object.middleName!);
        final lastNameOffset = object.lastName == null
            ? null
            : fbb.writeString(object.lastName!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firstNameOffset);
        fbb.addOffset(2, middleNameOffset);
        fbb.addOffset(3, lastNameOffset);
        fbb.addInt64(4, object.number);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = OBPerson()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..firstName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..middleName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..lastName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..number = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OBPerson] entity fields to define ObjectBox queries.
class OBPerson_ {
  /// See [OBPerson.id].
  static final id = obx.QueryIntegerProperty<OBPerson>(
    _entities[0].properties[0],
  );

  /// See [OBPerson.firstName].
  static final firstName = obx.QueryStringProperty<OBPerson>(
    _entities[0].properties[1],
  );

  /// See [OBPerson.middleName].
  static final middleName = obx.QueryStringProperty<OBPerson>(
    _entities[0].properties[2],
  );

  /// See [OBPerson.lastName].
  static final lastName = obx.QueryStringProperty<OBPerson>(
    _entities[0].properties[3],
  );

  /// See [OBPerson.number].
  static final number = obx.QueryIntegerProperty<OBPerson>(
    _entities[0].properties[4],
  );
}
